config/routes.rb
SimpleK::Application.routes.draw do
  get "home/index"
  
  get 'login', :to => 'twitter#login', :as => "login"
  get 'logout', :to => 'twitter#logout', :as => "logout"
  
  get "twitter/after_login"

  
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :screen_name, :presence => true, :length => {:maximum => 255}, :uniqueness => true
  validates :oauth_secret, :presence => true
  validates :oauth_token, :presence => true
  
  # generate twitter's url for getting profile image using screen name
  def profile_url
    "http://twitter.com/#{self.screen_name}"
  end

  def profile_image
    "http://api.twitter.com/1/users/profile_image/#{self.screen_name}.json?size=normal"
  end

  # searches user using screen name or create new one with specific oauth token and secret
  def self.login(credentials, result)
    # use exiting record for already registered users
    u = User.where(:screen_name => credentials.screen_name).first
    # Creates record in table user for new user
    u ||= User.create(:screen_name => credentials.screen_name, :oauth_token => result.token, :oauth_secret => result.secret)
  end

  # create complete Twitter::Client object for working with twitter under specific user account
  def client
    options = {
        :consumer_key => APP_CONFIG[:twitter][:consumer_token],
        :consumer_secret => APP_CONFIG[:twitter][:consumer_secret],
        :oauth_token => self.oauth_token,
        :oauth_token_secret => self.oauth_secret
    }
    Twitter::Client.new(options)
  end
  
end

# == Schema Information
#
# Table name: users
#
#  id           :integer         not null, primary key
#  screen_name  :string(255)
#  oauth_token  :string(255)
#  oauth_secret :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   # finds current user record in table 'users' using id stored in session
  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end

  # save user id in session
  def set_current_user(user)
    @current_user = user
    session[:current_user_id] = (user ? user.id : nil)
  end

  def authorized?
    !!current_user
  end

  # add notice message, which will be printed in layout with green color
  def push_notice_message(msg)
    push_message(:notice, msg)
  end

  # add error message, which will be printed in layout with red color
  def push_error_message(msg)
    push_message(:error, msg)
  end

  # add message
  def push_message(type, msg)
    session[:system_message] ||= {:notice => [], :error => []}
    if msg.is_a?(::Hash)
      msg.full_messages.each do |m|
        session[:system_message][type] << m
      end
    else
      session[:system_message][type] << msg
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/twitter_controller.rb
# This class aggregate all functionality for working with Twitter API. Twitter login and tweeting are implemented here.
# all methods requires authorization, except ones for for authorization
class TwitterController < ApplicationController

  TWITTER_API_URL = "https://api.twitter.com"

  # perform first step in oauth authenticating
  def login
    # get request token
    p "before"
    request_token = twitter_oauth.get_request_token(:oauth_callback => oauth_callback)

    p "request_token: "
    p request_token

    session['rtoken'] = request_token.token
    session['rsecret'] = request_token.secret

    # redirect to Twitter's authenticating page
    redirect_to twitter_authenticate(request_token.token)
  rescue OAuth::Error => e
    logger.error("OAuth error: #{e} \n #{e.backtrace.join("\n")}")
    push_error_message t(:oauth_error)
    redirect_to root_url
  end

  # perform logout
  def logout
    # simply clean current user value in session
    set_current_user(nil)
    redirect_to root_url
  end

  # is redirected by Twitter after authenticating.
  def after_login
    # user doen't allowed
    raise t(:twitter_denided) if params[:denied]

    # get OAuth access token
    result = OAuth::RequestToken.new(twitter_oauth, session['rtoken'], session['rsecret']).
        get_access_token(:oauth_verifier => params[:oauth_verifier])

    options = {:consumer_key => APP_CONFIG[:twitter][:consumer_token],
               :consumer_secret => APP_CONFIG[:twitter][:consumer_secret],
               :oauth_token => result.token,
               :oauth_token_secret => result.secret}

    # get twitter screen name using got access token
    client = Twitter::Client.new(options)
    credentials = client.verify_credentials

    # search user using screen name
    user = User.login(credentials, result)

    # Sets current user variable
    set_current_user user

    redirect_to root_url

  rescue OAuth::Error => e
    logger.error("OAuth error: #{e} \n #{e.backtrace.join("\n")}")
    push_error_message t(:oauth_error)
    redirect_to root_url
  rescue Twitter::Error => e
    logger.error("Twitter error: #{e} \n #{e.backtrace.join("\n")}")
    push_error_message t(:twitter_error)
    redirect_to root_url
  rescue StandardError => e
    push_error_message e.to_s
    redirect_to root_url
  end

  private

  # return OAuth::Consumer object
  def twitter_oauth
    p APP_CONFIG[:twitter][:consumer_token]
    p APP_CONFIG[:twitter][:consumer_secret]
    p TWITTER_API_URL
    
    OAuth::Consumer.new(APP_CONFIG[:twitter][:consumer_token], APP_CONFIG[:twitter][:consumer_secret],
                        {:site => TWITTER_API_URL, :request_endpoint => TWITTER_API_URL})
  end

  # generate callback url for twitter login
  def oauth_callback
    @callback_url ||= "http://#{request.host_with_port}/twitter/after_login"
  end

  def twitter_authenticate(oauth_token)
    "https://api.twitter.com/oauth/authenticate?oauth_token=#{oauth_token}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def system_messages
    return "" if session[:system_message].blank?
    str = render(:partial => "layouts/sys_messages")
    session[:system_message] = nil
    str.html_safe
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/home/index.html.erb
<p>landing content</p>

app/views/layouts/_footer.html.erb
<p>&copy; Company 2011</p>

app/views/layouts/_header.html.erb
<div class="header">
  
  
  <% if controller.authorized? %>
    
    <span class="pull-right">
      <ul class="nav" >
        <li>
          <%= link_to controller.current_user.screen_name, controller.current_user.profile_url %>
        </li>
        <li>
          <%= link_to "logout", logout_url, {:id => "logout"} %>
        </li>
      </ul>
    </span>
    
    <form action="" class="pull-right">
      <%= link_to(image_tag(controller.current_user.profile_image, :size => "30x30"), controller.current_user.profile_url) %>
    </form>
    
    
  <% else %>
    <form action="" class="pull-right">    
      <%= link_to image_tag("/images/twitter_button.gif"), login_url, :id => "twitter_login_but" %>
    </form>      
  <% end %>
  
  <div id="menu-box">
    <div id="system_message">
      <%= system_messages %>
    </div>
  </div>
  
</div>

app/views/layouts/_sys_messages.erb
<% session[:system_message][:notice].each do |msg| %>
    <div class="notice"> <%= msg %> </div> </br>
<% end %>

<% session[:system_message][:error].each do |msg| %>
    <div class="error"> <%= msg %> </div> </br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SimpleK</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
      .container > footer p {
        text-align: center; /* center align it with the container */
      }
      .container {
        width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
      }

      /* The white background content wrapper */
      .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
        -webkit-border-radius: 0 0 6px 6px;
           -moz-border-radius: 0 0 6px 6px;
                border-radius: 0 0 6px 6px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

      /* Page header tweaks */
      .page-header {
        background-color: #f5f5f5;
        padding: 20px 20px 10px;
        margin: -20px -20px 20px;
      }

      /* Styles you shouldn't keep as they are for displaying this base example only */
      .content .span10,
      .content .span4 {
        min-height: 500px;
      }
      /* Give a quick and non-cross-browser friendly divider */
      .content .span4 {
        margin-left: 0;
        padding-left: 19px;
        border-left: 1px solid #eee;
      }

      .topbar .btn {
        border: 0;
      }

    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Project name</a>
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><%= link_to "Sandbox", logout_url %></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          
             <%= render :partial => "layouts/header" %>
          
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
          <h1>Page name <small>Supporting text or tagline</small></h1>
        </div>
        <div class="row">
          <div class="span10">
            <h2>Main content</h2>
            <%= yield %>
          </div>
          <div class="span4">
            <h3>Secondary content</h3>
          </div>
        </div>
      </div>

      <footer>
         <%= render :partial => "layouts/footer" %>
      </footer>

    </div> <!-- /container -->

  </body>
</html>